"""Export an analyser result dict as a standalone HTML or Markdown report.

The terminal renderer in :mod:`logwatch.report` is for a TTY; these exporters
produce artefacts you keep or share:

* :func:`render_html` - a single self-contained ``.html`` file (inline CSS, no
  external assets, no JavaScript) that you can email, attach to a ticket or
  open from a file share. Opens fine offline.
* :func:`render_markdown` - a ``.md`` document that drops cleanly into a GitHub
  issue, a wiki or a CI job summary.

Both take the same plain dict produced by :mod:`logwatch.analyzers` (the very
dict that ``--json`` prints), so they stay in lock-step with the rest of the
tool and remain pure string builders with no I/O. Everything here is standard
library only (``html.escape`` for safe HTML, plain f-strings for Markdown).

Security note: log fields (paths, user-agents, usernames) are attacker-
controlled, so every value placed into the HTML is run through
:func:`html.escape`. That is what makes it safe to open a report built from a
hostile log in a browser.
"""

from __future__ import annotations

from datetime import datetime, timezone
from html import escape
from typing import Dict, List, Optional, Sequence

# Human-friendly names for the suspicious-request categories (kept in sync with
# report.py; duplicated rather than imported to keep these modules decoupled).
_CATEGORY_LABELS = {
    "path_traversal": "Path traversal (../)",
    "sqli": "SQL injection pattern",
    "xss": "Cross-site scripting probe",
    "scanner_path": "Scanner / recon path",
    "sensitive_file": "Sensitive-file probe",
    "oversized_query": "Oversized query string",
    "bad_method": "Unusual HTTP method",
}

# The disclaimer printed near IP tables in every export: logwatch is GeoIP-free
# on purpose (zero dependencies, no bundled database, no network lookups), so it
# must not pretend to know an address's owner, ASN or country.
ASN_DISCLAIMER = (
    "logwatch does not resolve IP ownership, ASN or geolocation - it ships with "
    "no GeoIP/ASN database and makes no network calls. To attribute an address, "
    "look it up yourself (e.g. an RDAP/whois query such as "
    "`whois <ip>`, or your provider's threat-intel feed)."
)


def _human_bytes(num: int) -> str:
    """Format a byte count as a compact human string (e.g. 12.3 MB)."""
    value = float(num)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if value < 1024 or unit == "TB":
            if unit == "B":
                return f"{int(value)} {unit}"
            return f"{value:.1f} {unit}"
        value /= 1024
    return f"{num} B"


def _now_stamp() -> str:
    """Return a UTC timestamp for the 'generated at' line."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


# ===========================================================================
# Markdown
# ===========================================================================

def _md_table(headers: Sequence[str], rows: Sequence[Sequence[object]]) -> List[str]:
    """Render a GitHub-flavoured Markdown table as a list of lines."""
    if not rows:
        return ["_(none)_", ""]
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        cells = [str(c).replace("|", "\\|") for c in row]
        out.append("| " + " | ".join(cells) + " |")
    out.append("")
    return out


def render_markdown(data: Dict, top_n: int) -> str:
    """Build a Markdown report from an analyser result dict."""
    if data.get("kind") == "auth":
        return _markdown_auth(data, top_n)
    return _markdown_access(data, top_n)


def _md_common_header(data: Dict, title: str) -> List[str]:
    risk = data.get("risk", "LOW")
    emoji = {"LOW": "🟢", "MEDIUM": "🟡", "HIGH": "🔴"}.get(risk, "⚪")
    out = [
        f"# {title}",
        "",
        f"_Generated by logwatch at {_now_stamp()}._",
        "",
        f"**Risk: {emoji} {risk}**",
        "",
    ]
    return out


def _markdown_access(data: Dict, top_n: int) -> str:
    out = _md_common_header(data, "HTTP access log report")

    span = data["time_span"]
    out += ["## Overview", ""]
    out += _md_table(
        ["Metric", "Value"],
        [
            ("Lines read", data["files_lines"]),
            ("Parsed requests", data["parsed"]),
            ("Unparsed lines", data["unparsed"]),
            ("Unique client IPs", data["unique_ips"]),
            ("Total bytes sent", _human_bytes(data["total_bytes"])),
            ("Time span", f"{span['first']} -> {span['last']}"),
            (
                "Peak req/min",
                f"{data['peak_minute']['count']} at {data['peak_minute']['minute']}"
                if data["peak_minute"]["count"]
                else "n/a",
            ),
        ],
    )

    out += ["## Status codes", ""]
    out += _md_table(
        ["Class", "Count"],
        [(k, v) for k, v in data["status_classes"].items()],
    )

    out += [f"## Top {top_n} client IPs", ""]
    out += _md_table(["IP", "Requests"], data["top_ips"])
    out += [f"_{ASN_DISCLAIMER}_", ""]

    out += [f"## Top {top_n} paths", ""]
    out += _md_table(["Path", "Hits"], data["top_paths"])

    out += [f"## Top {top_n} user-agents", ""]
    out += _md_table(["User-Agent", "Hits"], data["top_agents"])

    susp = data["suspicious"]
    out += [f"## Suspicious requests ({susp['total']})", ""]
    if susp.get("suppressed"):
        out += [
            f"_{susp['suppressed']} request(s) from allow-listed sources were "
            "suppressed._",
            "",
        ]
    if susp["total"] == 0:
        out += ["No suspicious requests detected.", ""]
    else:
        out += ["### By category", ""]
        out += _md_table(
            ["Category", "Count"],
            [(_CATEGORY_LABELS.get(c, c), n) for c, n in susp["by_category"]],
        )
        out += ["### Offending IPs", ""]
        out += _md_table(["IP", "Flags"], susp["by_ip"])
        out += [f"_{ASN_DISCLAIMER}_", ""]
        out += ["### Sample flagged requests", ""]
        out += _md_table(
            ["IP", "Method", "Path", "Why"],
            [
                (s["ip"], s["method"], s["path"], ", ".join(s["categories"]))
                for s in susp["samples"]
            ],
        )

    return "\n".join(out).rstrip() + "\n"


def _markdown_auth(data: Dict, top_n: int) -> str:
    out = _md_common_header(data, "SSH auth log report")

    span = data["time_span"]
    out += ["## Overview", ""]
    out += _md_table(
        ["Metric", "Value"],
        [
            ("Lines read", data["files_lines"]),
            ("Parsed events", data["parsed"]),
            ("Unparsed lines", data["unparsed"]),
            ("Failed logins", data["failed_logins"]),
            ("Accepted logins", data["accepted_logins"]),
            ("Time span", f"{span['first']} -> {span['last']}"),
        ],
    )

    bf = data["bruteforce"]
    out += [
        f"## Brute-force suspects (>= {bf['threshold']} fails / "
        f"{bf['window_minutes']} min)",
        "",
    ]
    if not bf["hits"]:
        out += ["No brute-force activity detected.", ""]
    else:
        out += _md_table(
            ["IP", "Fails", "Peak/win", "Scope", "Users tried"],
            [
                (
                    h["ip"],
                    h["failed_count"],
                    h["peak_in_window"],
                    h.get("scope", "other"),
                    ", ".join(h["users_tried"]),
                )
                for h in bf["hits"]
            ],
        )
        if any(h.get("scope") == "private" for h in bf["hits"]):
            out += [
                "> **Note:** one or more attacks originate from a PRIVATE "
                "address - possible lateral movement / internal host.",
                "",
            ]
        out += [f"_{ASN_DISCLAIMER}_", ""]

    out += [f"## Top {top_n} attacking IPs", ""]
    out += _md_table(["IP", "Failures"], data["top_attacking_ips"])

    out += [f"## Top {top_n} invalid users tried", ""]
    out += _md_table(["Username", "Attempts"], data["top_invalid_users"])

    out += ["## Accepted logins", ""]
    out += _md_table(["Username", "Logins"], data["accepted_users"])

    return "\n".join(out).rstrip() + "\n"


# ===========================================================================
# HTML
# ===========================================================================

_HTML_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica,
    Arial, sans-serif;
  line-height: 1.5; margin: 0; padding: 2rem;
  background: #f6f8fa; color: #1f2328;
}
.wrap { max-width: 1000px; margin: 0 auto; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
h2 { font-size: 1.15rem; margin: 2rem 0 .6rem; border-bottom: 1px solid #d0d7de;
     padding-bottom: .3rem; }
h3 { font-size: 1rem; margin: 1.2rem 0 .4rem; }
.meta { color: #57606a; font-size: .85rem; margin-bottom: 1rem; }
table { border-collapse: collapse; width: 100%; margin: .4rem 0 1rem;
        font-size: .9rem; background: #fff; }
th, td { text-align: left; padding: .4rem .6rem; border: 1px solid #d0d7de; }
th { background: #eaeef2; font-weight: 600; }
td.num { text-align: right; font-variant-numeric: tabular-nums; }
code, td.mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas,
                monospace; font-size: .85em; }
.badge { display: inline-block; padding: .15rem .6rem; border-radius: 999px;
         font-weight: 700; font-size: .85rem; color: #fff; }
.risk-LOW { background: #1a7f37; }
.risk-MEDIUM { background: #9a6700; }
.risk-HIGH { background: #cf222e; }
.note { background: #fff8c5; border: 1px solid #d4a72c; border-radius: 6px;
        padding: .6rem .8rem; margin: .6rem 0; font-size: .85rem; }
.disclaimer { color: #57606a; font-size: .8rem; margin: .2rem 0 1rem; }
.empty { color: #57606a; font-style: italic; }
footer { margin-top: 2.5rem; color: #8c959f; font-size: .8rem;
         border-top: 1px solid #d0d7de; padding-top: .8rem; }
@media (prefers-color-scheme: dark) {
  body { background: #0d1117; color: #e6edf3; }
  h2, th { border-color: #30363d; }
  th { background: #161b22; }
  td { border-color: #30363d; }
  table { background: #0d1117; }
  .meta, .disclaimer, footer { color: #8b949e; }
  .note { background: #2d2200; border-color: #9e6a03; }
}
""".strip()


def _h_table(
    headers: Sequence[str],
    rows: Sequence[Sequence[object]],
    *,
    num_cols: Sequence[int] = (),
    mono_cols: Sequence[int] = (),
) -> str:
    """Render an HTML table with every cell escaped. Empty rows -> a placeholder."""
    if not rows:
        return '<p class="empty">(none)</p>'
    thead = "".join(f"<th>{escape(str(h))}</th>" for h in headers)
    body_rows = []
    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            cls = []
            if i in num_cols:
                cls.append("num")
            if i in mono_cols:
                cls.append("mono")
            attr = f' class="{" ".join(cls)}"' if cls else ""
            cells.append(f"<td{attr}>{escape(str(cell))}</td>")
        body_rows.append("<tr>" + "".join(cells) + "</tr>")
    return (
        "<table><thead><tr>"
        + thead
        + "</tr></thead><tbody>"
        + "".join(body_rows)
        + "</tbody></table>"
    )


def _h_disclaimer() -> str:
    return f'<p class="disclaimer">{escape(ASN_DISCLAIMER)}</p>'


def render_html(data: Dict, top_n: int) -> str:
    """Build a complete, self-contained HTML document from a result dict."""
    if data.get("kind") == "auth":
        body = _html_auth_body(data, top_n)
        title = "SSH auth log report"
    else:
        body = _html_access_body(data, top_n)
        title = "HTTP access log report"

    risk = escape(str(data.get("risk", "LOW")))
    parts = [
        "<!DOCTYPE html>",
        '<html lang="en">',
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>logwatch - {escape(title)}</title>",
        f"<style>{_HTML_CSS}</style>",
        "</head>",
        "<body><div class='wrap'>",
        f"<h1>{escape(title)}</h1>",
        f'<p class="meta">Generated by logwatch at {escape(_now_stamp())} '
        f'&middot; <span class="badge risk-{risk}">RISK: {risk}</span></p>',
        body,
        "<footer>Generated by logwatch &middot; zero-dependency log analysis &amp; "
        "security reporting. Analyse only logs you own or are authorised to "
        "inspect.</footer>",
        "</div></body></html>",
    ]
    return "\n".join(parts) + "\n"


def _html_access_body(data: Dict, top_n: int) -> str:
    span = data["time_span"]
    peak = data["peak_minute"]
    out: List[str] = ["<h2>Overview</h2>"]
    out.append(
        _h_table(
            ["Metric", "Value"],
            [
                ("Lines read", data["files_lines"]),
                ("Parsed requests", data["parsed"]),
                ("Unparsed lines", data["unparsed"]),
                ("Unique client IPs", data["unique_ips"]),
                ("Total bytes sent", _human_bytes(data["total_bytes"])),
                ("Time span", f"{span['first']} -> {span['last']}"),
                (
                    "Peak req/min",
                    f"{peak['count']} at {peak['minute']}" if peak["count"] else "n/a",
                ),
            ],
        )
    )

    out.append("<h2>Status codes</h2>")
    out.append(
        _h_table(
            ["Class", "Count"],
            list(data["status_classes"].items()),
            num_cols=(1,),
        )
    )

    out.append(f"<h2>Top {top_n} client IPs</h2>")
    out.append(_h_table(["IP", "Requests"], data["top_ips"], num_cols=(1,), mono_cols=(0,)))
    out.append(_h_disclaimer())

    out.append(f"<h2>Top {top_n} paths</h2>")
    out.append(_h_table(["Path", "Hits"], data["top_paths"], num_cols=(1,), mono_cols=(0,)))

    out.append(f"<h2>Top {top_n} user-agents</h2>")
    out.append(_h_table(["User-Agent", "Hits"], data["top_agents"], num_cols=(1,)))

    susp = data["suspicious"]
    out.append(f"<h2>Suspicious requests ({escape(str(susp['total']))})</h2>")
    if susp.get("suppressed"):
        out.append(
            f'<p class="note">{escape(str(susp["suppressed"]))} request(s) from '
            "allow-listed sources were suppressed.</p>"
        )
    if susp["total"] == 0:
        out.append('<p class="empty">No suspicious requests detected.</p>')
    else:
        out.append("<h3>By category</h3>")
        out.append(
            _h_table(
                ["Category", "Count"],
                [(_CATEGORY_LABELS.get(c, c), n) for c, n in susp["by_category"]],
                num_cols=(1,),
            )
        )
        out.append("<h3>Offending IPs</h3>")
        out.append(_h_table(["IP", "Flags"], susp["by_ip"], num_cols=(1,), mono_cols=(0,)))
        out.append(_h_disclaimer())
        out.append("<h3>Sample flagged requests</h3>")
        out.append(
            _h_table(
                ["IP", "Method", "Path", "Why"],
                [
                    (s["ip"], s["method"], s["path"], ", ".join(s["categories"]))
                    for s in susp["samples"]
                ],
                mono_cols=(0, 2),
            )
        )
    return "\n".join(out)


def _html_auth_body(data: Dict, top_n: int) -> str:
    span = data["time_span"]
    out: List[str] = ["<h2>Overview</h2>"]
    out.append(
        _h_table(
            ["Metric", "Value"],
            [
                ("Lines read", data["files_lines"]),
                ("Parsed events", data["parsed"]),
                ("Unparsed lines", data["unparsed"]),
                ("Failed logins", data["failed_logins"]),
                ("Accepted logins", data["accepted_logins"]),
                ("Time span", f"{span['first']} -> {span['last']}"),
            ],
        )
    )

    bf = data["bruteforce"]
    out.append(
        f"<h2>Brute-force suspects (&ge; {escape(str(bf['threshold']))} fails / "
        f"{escape(str(bf['window_minutes']))} min)</h2>"
    )
    if not bf["hits"]:
        out.append('<p class="empty">No brute-force activity detected.</p>')
    else:
        out.append(
            _h_table(
                ["IP", "Fails", "Peak/win", "Scope", "Users tried"],
                [
                    (
                        h["ip"],
                        h["failed_count"],
                        h["peak_in_window"],
                        h.get("scope", "other"),
                        ", ".join(h["users_tried"]),
                    )
                    for h in bf["hits"]
                ],
                num_cols=(1, 2),
                mono_cols=(0,),
            )
        )
        if any(h.get("scope") == "private" for h in bf["hits"]):
            out.append(
                '<p class="note"><strong>Note:</strong> one or more attacks '
                "originate from a PRIVATE address - possible lateral movement / "
                "internal host.</p>"
            )
        out.append(_h_disclaimer())

    out.append(f"<h2>Top {top_n} attacking IPs</h2>")
    out.append(
        _h_table(["IP", "Failures"], data["top_attacking_ips"], num_cols=(1,), mono_cols=(0,))
    )

    out.append(f"<h2>Top {top_n} invalid users tried</h2>")
    out.append(_h_table(["Username", "Attempts"], data["top_invalid_users"], num_cols=(1,)))

    out.append("<h2>Accepted logins</h2>")
    out.append(_h_table(["Username", "Logins"], data["accepted_users"], num_cols=(1,)))
    return "\n".join(out)
